package com.arisux.starway.client.model.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * MK50 - cybercat5555
 * Created using Tabula 7.0.1
 */
public class ModelSuitMK50 extends ModelBiped
{
    public ModelRenderer rArm;
    public ModelRenderer rLeg;
    public ModelRenderer head;
    public ModelRenderer body;
    public ModelRenderer lArm;
    public ModelRenderer lLeg;
    public ModelRenderer leggings_rSleeve;
    public ModelRenderer leggings_rGauntlet;
    public ModelRenderer leggings_rGlove;
    public ModelRenderer chestplate_rShoulderPad01a;
    public ModelRenderer chestplate_rShoulderPad01b;
    public ModelRenderer chestplate_rShoulderPad02;
    public ModelRenderer chestplate_rShoulderPad03a;
    public ModelRenderer chestplate_rShoulderStrap;
    public ModelRenderer chestplate_rShoulderPad03b;
    public ModelRenderer leggings_rLegSuit;
    public ModelRenderer boots_rBoots01;
    public ModelRenderer leggings_rPad;
    public ModelRenderer boots_rBoots02;
    public ModelRenderer boots_rBoots03;
    public ModelRenderer boots_rBoots04;
    public ModelRenderer boots_rBoots05;
    public ModelRenderer helmet_Bubble;
    public ModelRenderer helmet_lFrameUpper;
    public ModelRenderer helmet_rFrameUpper;
    public ModelRenderer helmet_tFrame;
    public ModelRenderer helmet_TubeConnector;
    public ModelRenderer helmet_mTubeConnector2;
    public ModelRenderer helmet_lTubeConnector;
    public ModelRenderer helmet_rTubeConnector;
    public ModelRenderer helmet_LampStand;
    public ModelRenderer helmet_Lamp2;
    public ModelRenderer helmet_Lamp3;
    public ModelRenderer helmet_Lamp1;
    public ModelRenderer helmet_Lamp5;
    public ModelRenderer helmet_LampLense;
    public ModelRenderer helmet_tube01;
    public ModelRenderer helmet_tube02;
    public ModelRenderer helmet_tube03;
    public ModelRenderer helmet_tube04;
    public ModelRenderer helmet_tube05;
    public ModelRenderer leggings_bodysuit;
    public ModelRenderer chestplate_plate01;
    public ModelRenderer chestplate_mStomachPlate;
    public ModelRenderer chestplate_airtankFrameUpper;
    public ModelRenderer chestplate_plate02;
    public ModelRenderer chestplate_plate03;
    public ModelRenderer chestplate_plate04;
    public ModelRenderer chestplate_lBelt03;
    public ModelRenderer chestplate_rBelt03;
    public ModelRenderer chestplate_rBelt04;
    public ModelRenderer chestplate_lBelt04;
    public ModelRenderer chestplate_lBelt07;
    public ModelRenderer chestplate_rBelt07;
    public ModelRenderer chestplate_lBelt09;
    public ModelRenderer chestplate_rBelt09;
    public ModelRenderer chestplate_lStomachPlate;
    public ModelRenderer chestplate_rStomachPlate;
    public ModelRenderer chestplate_lBelt01;
    public ModelRenderer chestplate_rBelt01;
    public ModelRenderer chestplate_lBelt02;
    public ModelRenderer chestplate_rBelt02;
    public ModelRenderer chestplate_mBelt01;
    public ModelRenderer chestplate_mBelt02;
    public ModelRenderer chestplate_mBelt03;
    public ModelRenderer chestplate_mBelt04;
    public ModelRenderer chestplate_tankPanel;
    public ModelRenderer chestplate_lAirtankFrame;
    public ModelRenderer chestplate_rAirtankFrame;
    public ModelRenderer chestplate_lCanister;
    public ModelRenderer chestplate_rCanister;
    public ModelRenderer chestplate_tubeConnector;
    public ModelRenderer chestplate_airtankFrameBottom;
    public ModelRenderer chestplate_lBelt05;
    public ModelRenderer chestplate_rBelt05;
    public ModelRenderer chestplate_lBelt06;
    public ModelRenderer chestplate_rBelt06;
    public ModelRenderer chestplate_lBelt08;
    public ModelRenderer chestplate_rBelt08;
    public ModelRenderer leggings_lSleeve;
    public ModelRenderer chestplate_lShoulderPad01a;
    public ModelRenderer leggings_lGauntlet;
    public ModelRenderer leggings_lGlove;
    public ModelRenderer chestplate_lShoulderPad01b;
    public ModelRenderer chestplate_lShoulderPad02;
    public ModelRenderer chestplate_lShoulderPad03a;
    public ModelRenderer chestplate_lShoulderStrap;
    public ModelRenderer chestplate_lShoulderPad03b;
    public ModelRenderer leggings_lLegSuit;
    public ModelRenderer boots_lBoots01;
    public ModelRenderer leggings_lPad;
    public ModelRenderer boots_lBoots02;
    public ModelRenderer boots_lBoots03;
    public ModelRenderer boots_lBoots04;
    public ModelRenderer boots_lBoots05;

    public ModelSuitMK50()
    {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.chestplate_rBelt03 = new ModelRenderer(this, 122, 4);
        this.chestplate_rBelt03.mirror = true;
        this.chestplate_rBelt03.setRotationPoint(-1.15F, 6.35F, -1.9F);
        this.chestplate_rBelt03.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.chestplate_rBelt07 = new ModelRenderer(this, 121, 0);
        this.chestplate_rBelt07.mirror = true;
        this.chestplate_rBelt07.setRotationPoint(-3.05F, 6.25F, -1.9F);
        this.chestplate_rBelt07.addBox(-1.5F, -0.5F, -0.5F, 2, 1, 1, 0.0F);
        this.chestplate_rShoulderPad01b = new ModelRenderer(this, 95, 95);
        this.chestplate_rShoulderPad01b.mirror = true;
        this.chestplate_rShoulderPad01b.setRotationPoint(0.0F, 0.0F, 0.6F);
        this.chestplate_rShoulderPad01b.addBox(-3.3F, -2.1F, -0.45F, 5, 3, 3, 0.0F);
        this.helmet_LampLense = new ModelRenderer(this, 51, 69);
        this.helmet_LampLense.setRotationPoint(0.0F, 0.0F, -1.5F);
        this.helmet_LampLense.addBox(-1.5F, -1.0F, 0.0F, 3, 2, 1, 0.0F);
        this.chestplate_lBelt04 = new ModelRenderer(this, 122, 4);
        this.chestplate_lBelt04.setRotationPoint(1.95F, 1.25F, -1.9F);
        this.chestplate_lBelt04.addBox(-0.5F, -2.0F, -0.5F, 1, 2, 1, 0.0F);
        this.boots_lBoots05 = new ModelRenderer(this, 0, 118);
        this.boots_lBoots05.setRotationPoint(0.0F, 10.6F, -1.5F);
        this.boots_lBoots05.addBox(-2.0F, -0.5F, -2.41F, 4, 2, 6, 0.0F);
        this.body = new ModelRenderer(this, 16, 16);
        this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.0F);
        this.chestplate_lBelt05 = new ModelRenderer(this, 122, 4);
        this.chestplate_lBelt05.setRotationPoint(2.15F, 2.15F, 2.6F);
        this.chestplate_lBelt05.addBox(-0.5F, -2.0F, -0.5F, 1, 3, 1, 0.0F);
        this.chestplate_rBelt05 = new ModelRenderer(this, 122, 4);
        this.chestplate_rBelt05.mirror = true;
        this.chestplate_rBelt05.setRotationPoint(-2.15F, 2.15F, 2.6F);
        this.chestplate_rBelt05.addBox(-0.5F, -2.0F, -0.5F, 1, 3, 1, 0.0F);
        this.leggings_lGauntlet = new ModelRenderer(this, 45, 84);
        this.leggings_lGauntlet.setRotationPoint(1.0F, 0.0F, 0.0F);
        this.leggings_lGauntlet.addBox(2.2F, 6.0F, -1.0F, 1, 3, 2, 0.0F);
        this.helmet_LampStand = new ModelRenderer(this, 73, 83);
        this.helmet_LampStand.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_LampStand.addBox(-1.0F, -10.1F, 2.5F, 2, 2, 1, 0.0F);
        this.setRotateAngle(helmet_LampStand, 0.20943951023931953F, -0.0F, 0.0F);
        this.boots_lBoots02 = new ModelRenderer(this, 2, 103);
        this.boots_lBoots02.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.boots_lBoots02.addBox(-2.2F, 9.0F, -1.9F, 1, 3, 4, 0.0F);
        this.chestplate_lShoulderPad01a = new ModelRenderer(this, 74, 93);
        this.chestplate_lShoulderPad01a.setRotationPoint(0.6F, -0.5F, 0.0F);
        this.chestplate_lShoulderPad01a.addBox(-1.7F, -2.1F, -3.15F, 5, 3, 4, 0.0F);
        this.setRotateAngle(chestplate_lShoulderPad01a, 0.0F, -0.0F, -0.22759093446006054F);
        this.helmet_tube03 = new ModelRenderer(this, 110, 40);
        this.helmet_tube03.setRotationPoint(0.0F, 1.8F, 0.0F);
        this.helmet_tube03.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.setRotateAngle(helmet_tube03, -0.4553564018453205F, 0.0F, 0.0F);
        this.chestplate_rShoulderPad02 = new ModelRenderer(this, 75, 103);
        this.chestplate_rShoulderPad02.mirror = true;
        this.chestplate_rShoulderPad02.setRotationPoint(-1.3F, 2.1F, 0.0F);
        this.chestplate_rShoulderPad02.addBox(-1.7F, -2.1F, -3.0F, 4, 2, 6, 0.0F);
        this.setRotateAngle(chestplate_rShoulderPad02, 0.0F, -0.0F, -0.091106186954104F);
        this.chestplate_rBelt02 = new ModelRenderer(this, 113, 4);
        this.chestplate_rBelt02.mirror = true;
        this.chestplate_rBelt02.setRotationPoint(-3.7F, 8.45F, -2.5F);
        this.chestplate_rBelt02.addBox(-1.0F, -1.0F, -0.5F, 1, 2, 6, 0.0F);
        this.chestplate_rBelt06 = new ModelRenderer(this, 115, 21);
        this.chestplate_rBelt06.mirror = true;
        this.chestplate_rBelt06.setRotationPoint(-1.95F, 0.65F, -1.9F);
        this.chestplate_rBelt06.addBox(-0.5F, -0.5F, -0.7F, 1, 1, 5, 0.0F);
        this.setRotateAngle(chestplate_rBelt06, 0.0F, -0.045553093477052F, 0.0F);
        this.chestplate_lShoulderPad02 = new ModelRenderer(this, 75, 103);
        this.chestplate_lShoulderPad02.setRotationPoint(0.4F, 2.1F, 0.0F);
        this.chestplate_lShoulderPad02.addBox(-1.4F, -2.1F, -3.0F, 4, 2, 6, 0.0F);
        this.setRotateAngle(chestplate_lShoulderPad02, 0.0F, -0.0F, 0.091106186954104F);
        this.helmet_TubeConnector = new ModelRenderer(this, 85, 76);
        this.helmet_TubeConnector.setRotationPoint(0.0F, 0.1F, 0.0F);
        this.helmet_TubeConnector.addBox(-1.0F, -9.5F, 2.0F, 2, 3, 3, 0.0F);
        this.leggings_lSleeve = new ModelRenderer(this, 48, 93);
        this.leggings_lSleeve.setRotationPoint(0.0F, 0.0F, -0.0F);
        this.leggings_lSleeve.addBox(-1.4F, -2.1F, -2.4F, 5, 12, 5, 0.0F);
        this.helmet_tube01 = new ModelRenderer(this, 110, 41);
        this.helmet_tube01.setRotationPoint(0.0F, -6.0F, 5.3F);
        this.helmet_tube01.addBox(-0.5F, 0.0F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(helmet_tube01, 0.5462880558742251F, 0.0F, 0.0F);
        this.chestplate_mBelt02 = new ModelRenderer(this, 112, 4);
        this.chestplate_mBelt02.setRotationPoint(0.0F, 11.1F, -2.3F);
        this.chestplate_mBelt02.addBox(-1.0F, 0.0F, -0.5F, 2, 1, 1, 0.0F);
        this.helmet_tFrame = new ModelRenderer(this, 84, 71);
        this.helmet_tFrame.setRotationPoint(0.0F, 0.1F, 0.6F);
        this.helmet_tFrame.addBox(-2.5F, -9.5F, 0.0F, 5, 1, 2, 0.0F);
        this.chestplate_lShoulderPad03a = new ModelRenderer(this, 75, 113);
        this.chestplate_lShoulderPad03a.setRotationPoint(-0.1F, 3.2F, 0.1F);
        this.chestplate_lShoulderPad03a.addBox(-0.4F, -3.1F, -2.9F, 3, 3, 5, 0.0F);
        this.setRotateAngle(chestplate_lShoulderPad03a, 0.0F, -0.0F, 0.22759093446006054F);
        this.chestplate_rBelt04 = new ModelRenderer(this, 122, 4);
        this.chestplate_rBelt04.mirror = true;
        this.chestplate_rBelt04.setRotationPoint(-1.95F, 1.25F, -1.9F);
        this.chestplate_rBelt04.addBox(-0.5F, -2.0F, -0.5F, 1, 2, 1, 0.0F);
        this.chestplate_lStomachPlate = new ModelRenderer(this, 90, 0);
        this.chestplate_lStomachPlate.setRotationPoint(0.0F, 0.5F, 0.0F);
        this.chestplate_lStomachPlate.addBox(0.2F, 7.3F, -3.5F, 2, 4, 1, 0.0F);
        this.chestplate_rAirtankFrame = new ModelRenderer(this, 85, 22);
        this.chestplate_rAirtankFrame.mirror = true;
        this.chestplate_rAirtankFrame.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_rAirtankFrame.addBox(-2.99F, 5.4F, 1.59F, 1, 5, 3, 0.0F);
        this.chestplate_tankPanel = new ModelRenderer(this, 96, 23);
        this.chestplate_tankPanel.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_tankPanel.addBox(-2.5F, 1.7F, 0.9F, 5, 2, 3, 0.0F);
        this.setRotateAngle(chestplate_tankPanel, 0.22759093446006054F, 0.0F, 0.0F);
        this.leggings_bodysuit = new ModelRenderer(this, 0, 66);
        this.leggings_bodysuit.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_bodysuit.addBox(-4.5F, -0.5F, -2.5F, 9, 13, 5, 0.0F);
        this.chestplate_plate04 = new ModelRenderer(this, 67, 16);
        this.chestplate_plate04.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_plate04.addBox(-2.5F, 5.8F, -2.6F, 5, 2, 1, 0.0F);
        this.chestplate_mBelt01 = new ModelRenderer(this, 107, 16);
        this.chestplate_mBelt01.setRotationPoint(0.0F, 8.45F, 2.5F);
        this.chestplate_mBelt01.addBox(-4.5F, -1.0F, -0.49F, 9, 2, 1, 0.0F);
        this.helmet_Lamp1 = new ModelRenderer(this, 60, 68);
        this.helmet_Lamp1.setRotationPoint(0.0F, -1.05F, -0.9F);
        this.helmet_Lamp1.addBox(-1.5F, -1.0F, -3.0F, 3, 2, 3, 0.0F);
        this.setRotateAngle(helmet_Lamp1, 0.22759093446006054F, -0.0F, 0.0F);
        this.boots_rBoots02 = new ModelRenderer(this, 2, 103);
        this.boots_rBoots02.mirror = true;
        this.boots_rBoots02.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.boots_rBoots02.addBox(1.1F, 9.0F, -1.9F, 1, 3, 4, 0.0F);
        this.chestplate_lBelt07 = new ModelRenderer(this, 121, 0);
        this.chestplate_lBelt07.setRotationPoint(3.05F, 6.25F, -1.9F);
        this.chestplate_lBelt07.addBox(-0.5F, -0.5F, -0.5F, 2, 1, 1, 0.0F);
        this.helmet_mTubeConnector2 = new ModelRenderer(this, 100, 78);
        this.helmet_mTubeConnector2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_mTubeConnector2.addBox(-1.5F, -6.7F, 4.0F, 3, 1, 2, 0.0F);
        this.helmet_tube02 = new ModelRenderer(this, 110, 40);
        this.helmet_tube02.setRotationPoint(0.0F, 0.9F, 0.0F);
        this.helmet_tube02.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.setRotateAngle(helmet_tube02, -0.18203784098300857F, 0.0F, 0.0F);
        this.chestplate_tubeConnector = new ModelRenderer(this, 105, 13);
        this.chestplate_tubeConnector.setRotationPoint(0.0F, 0.5F, 0.1F);
        this.chestplate_tubeConnector.addBox(-1.0F, -1.6F, 3.8F, 2, 1, 1, 0.0F);
        this.setRotateAngle(chestplate_tubeConnector, -0.5462880558742251F, 0.0F, 0.0F);
        this.chestplate_lAirtankFrame = new ModelRenderer(this, 85, 22);
        this.chestplate_lAirtankFrame.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_lAirtankFrame.addBox(1.99F, 5.4F, 1.59F, 1, 5, 3, 0.0F);
        this.helmet_rTubeConnector = new ModelRenderer(this, 105, 70);
        this.helmet_rTubeConnector.mirror = true;
        this.helmet_rTubeConnector.setRotationPoint(0.0F, 0.0F, 2.8F);
        this.helmet_rTubeConnector.addBox(-3.6F, -8.0F, 1.7F, 2, 4, 1, 0.0F);
        this.leggings_lPad = new ModelRenderer(this, 25, 90);
        this.leggings_lPad.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_lPad.addBox(-2.4F, 3.1F, -3.2F, 5, 6, 1, 0.0F);
        this.chestplate_rStomachPlate = new ModelRenderer(this, 90, 0);
        this.chestplate_rStomachPlate.mirror = true;
        this.chestplate_rStomachPlate.setRotationPoint(0.0F, 0.5F, 0.0F);
        this.chestplate_rStomachPlate.addBox(-2.2F, 7.3F, -3.5F, 2, 4, 1, 0.0F);
        this.leggings_lLegSuit = new ModelRenderer(this, 0, 86);
        this.leggings_lLegSuit.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_lLegSuit.addBox(-2.5F, -0.01F, -2.5F, 5, 9, 5, 0.0F);
        this.boots_lBoots03 = new ModelRenderer(this, 12, 112);
        this.boots_lBoots03.setRotationPoint(0.0F, 10.5F, -1.5F);
        this.boots_lBoots03.addBox(-0.9F, -1.5F, -0.8F, 3, 3, 1, 0.0F);
        this.leggings_rPad = new ModelRenderer(this, 25, 90);
        this.leggings_rPad.mirror = true;
        this.leggings_rPad.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_rPad.addBox(-2.6F, 3.1F, -3.2F, 5, 6, 1, 0.0F);
        this.leggings_rLegSuit = new ModelRenderer(this, 0, 86);
        this.leggings_rLegSuit.mirror = true;
        this.leggings_rLegSuit.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_rLegSuit.addBox(-2.5F, -0.01F, -2.5F, 5, 9, 5, 0.0F);
        this.rLeg = new ModelRenderer(this, 0, 16);
        this.rLeg.setRotationPoint(-1.9F, 12.0F, 0.1F);
        this.rLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        this.chestplate_rCanister = new ModelRenderer(this, 85, 31);
        this.chestplate_rCanister.mirror = true;
        this.chestplate_rCanister.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_rCanister.addBox(-2.05F, 5.3F, 2.1F, 2, 6, 2, 0.0F);
        this.chestplate_rShoulderPad01a = new ModelRenderer(this, 74, 93);
        this.chestplate_rShoulderPad01a.mirror = true;
        this.chestplate_rShoulderPad01a.setRotationPoint(-0.6F, -0.5F, 0.0F);
        this.chestplate_rShoulderPad01a.addBox(-3.3F, -2.1F, -3.15F, 5, 3, 4, 0.0F);
        this.setRotateAngle(chestplate_rShoulderPad01a, 0.0F, -0.0F, 0.22759093446006054F);
        this.chestplate_rShoulderPad03a = new ModelRenderer(this, 75, 113);
        this.chestplate_rShoulderPad03a.mirror = true;
        this.chestplate_rShoulderPad03a.setRotationPoint(-0.1F, 3.2F, 0.1F);
        this.chestplate_rShoulderPad03a.addBox(-2.4F, -3.1F, -2.9F, 3, 3, 5, 0.0F);
        this.setRotateAngle(chestplate_rShoulderPad03a, 0.0F, -0.0F, -0.22759093446006054F);
        this.helmet_tube05 = new ModelRenderer(this, 110, 40);
        this.helmet_tube05.setRotationPoint(0.0F, 1.8F, 0.0F);
        this.helmet_tube05.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.setRotateAngle(helmet_tube05, -0.27314402793711257F, 0.0F, 0.0F);
        this.rArm = new ModelRenderer(this, 40, 16);
        this.rArm.setRotationPoint(-5.0F, 2.0F, 0.0F);
        this.rArm.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        this.setRotateAngle(rArm, 0.0F, 0.0F, 0.10000736613927509F);
        this.chestplate_lCanister = new ModelRenderer(this, 85, 31);
        this.chestplate_lCanister.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_lCanister.addBox(0.05F, 5.3F, 2.2F, 2, 6, 2, 0.0F);
        this.chestplate_lBelt08 = new ModelRenderer(this, 121, 0);
        this.chestplate_lBelt08.setRotationPoint(3.05F, 7.75F, 2.0F);
        this.chestplate_lBelt08.addBox(-0.5F, -0.5F, -0.5F, 2, 1, 1, 0.0F);
        this.boots_rBoots05 = new ModelRenderer(this, 0, 118);
        this.boots_rBoots05.mirror = true;
        this.boots_rBoots05.setRotationPoint(0.0F, 10.6F, -1.5F);
        this.boots_rBoots05.addBox(-2.0F, -0.5F, -2.41F, 4, 2, 6, 0.0F);
        this.boots_lBoots04 = new ModelRenderer(this, 3, 112);
        this.boots_lBoots04.setRotationPoint(0.0F, 10.5F, -1.5F);
        this.boots_lBoots04.addBox(-2.15F, -1.5F, -0.8F, 2, 3, 1, 0.0F);
        this.chestplate_lBelt06 = new ModelRenderer(this, 115, 21);
        this.chestplate_lBelt06.setRotationPoint(1.95F, 0.65F, -1.9F);
        this.chestplate_lBelt06.addBox(-0.5F, -0.5F, -0.7F, 1, 1, 5, 0.0F);
        this.setRotateAngle(chestplate_lBelt06, 0.0F, 0.045553093477052F, 0.0F);
        this.lLeg = new ModelRenderer(this, 16, 48);
        this.lLeg.setRotationPoint(1.9F, 12.0F, 0.1F);
        this.lLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        this.boots_rBoots04 = new ModelRenderer(this, 3, 112);
        this.boots_rBoots04.mirror = true;
        this.boots_rBoots04.setRotationPoint(0.0F, 10.5F, -1.5F);
        this.boots_rBoots04.addBox(0.05F, -1.5F, -0.8F, 2, 3, 1, 0.0F);
        this.chestplate_lBelt09 = new ModelRenderer(this, 115, 21);
        this.chestplate_lBelt09.setRotationPoint(4.05F, 6.25F, -1.3F);
        this.chestplate_lBelt09.addBox(-0.5F, -0.5F, -0.7F, 1, 1, 5, 0.0F);
        this.chestplate_plate01 = new ModelRenderer(this, 67, 0);
        this.chestplate_plate01.setRotationPoint(0.0F, 0.0F, -0.6F);
        this.chestplate_plate01.addBox(-3.0F, 1.17F, -2.9F, 6, 2, 1, 0.0F);
        this.chestplate_mStomachPlate = new ModelRenderer(this, 99, 0);
        this.chestplate_mStomachPlate.setRotationPoint(0.0F, 0.5F, 0.0F);
        this.chestplate_mStomachPlate.addBox(-2.0F, 7.9F, -2.9F, 4, 4, 1, 0.0F);
        this.chestplate_airtankFrameBottom = new ModelRenderer(this, 96, 32);
        this.chestplate_airtankFrameBottom.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_airtankFrameBottom.addBox(-3.0F, 9.6F, 1.6F, 6, 1, 3, 0.0F);
        this.leggings_rGlove = new ModelRenderer(this, 45, 114);
        this.leggings_rGlove.mirror = true;
        this.leggings_rGlove.setRotationPoint(-1.9F, 2.8F, 0.0F);
        this.leggings_rGlove.addBox(-4.0F, 5.5F, -2.0F, 4, 3, 4, 0.0F);
        this.setRotateAngle(leggings_rGlove, 0.0F, 0.0F, -0.40980330836826856F);
        this.helmet_rFrameUpper = new ModelRenderer(this, 73, 52);
        this.helmet_rFrameUpper.mirror = true;
        this.helmet_rFrameUpper.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_rFrameUpper.addBox(-5.01F, -6.8F, -4.2F, 1, 10, 2, 0.0F);
        this.setRotateAngle(helmet_rFrameUpper, -1.0927506446736497F, -0.0F, 0.0F);
        this.chestplate_lBelt01 = new ModelRenderer(this, 111, 0);
        this.chestplate_lBelt01.setRotationPoint(1.9F, 9.1F, -2.5F);
        this.chestplate_lBelt01.addBox(-0.7F, -1.0F, -0.51F, 3, 2, 1, 0.0F);
        this.setRotateAngle(chestplate_lBelt01, 0.0F, 0.0F, -0.31869712141416456F);
        this.head = new ModelRenderer(this, 0, 0);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.0F);
        this.chestplate_lBelt02 = new ModelRenderer(this, 113, 4);
        this.chestplate_lBelt02.setRotationPoint(3.7F, 8.45F, -2.5F);
        this.chestplate_lBelt02.addBox(0.0F, -1.0F, -0.5F, 1, 2, 6, 0.0F);
        this.chestplate_lShoulderPad03b = new ModelRenderer(this, 93, 113);
        this.chestplate_lShoulderPad03b.setRotationPoint(-0.1F, 0.0F, 0.1F);
        this.chestplate_lShoulderPad03b.addBox(-0.3F, -3.1F, 1.65F, 3, 3, 1, 0.0F);
        this.chestplate_mBelt04 = new ModelRenderer(this, 99, 6);
        this.chestplate_mBelt04.setRotationPoint(0.0F, 11.15F, -1.4F);
        this.chestplate_mBelt04.addBox(-1.0F, 0.0F, -0.5F, 2, 1, 4, 0.0F);
        this.chestplate_rBelt08 = new ModelRenderer(this, 121, 0);
        this.chestplate_rBelt08.mirror = true;
        this.chestplate_rBelt08.setRotationPoint(-3.05F, 7.75F, 2.0F);
        this.chestplate_rBelt08.addBox(-1.5F, -0.5F, -0.5F, 2, 1, 1, 0.0F);
        this.helmet_tube04 = new ModelRenderer(this, 110, 40);
        this.helmet_tube04.setRotationPoint(0.0F, 1.7F, 0.0F);
        this.helmet_tube04.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.setRotateAngle(helmet_tube04, -0.36425021489121656F, 0.0F, 0.0F);
        this.helmet_Lamp2 = new ModelRenderer(this, 57, 75);
        this.helmet_Lamp2.setRotationPoint(0.0F, -10.0F, 3.3F);
        this.helmet_Lamp2.addBox(-1.5F, -2.0F, -1.5F, 3, 2, 3, 0.0F);
        this.setRotateAngle(helmet_Lamp2, -0.27314402793711257F, -0.0F, 0.0F);
        this.chestplate_rBelt09 = new ModelRenderer(this, 115, 21);
        this.chestplate_rBelt09.mirror = true;
        this.chestplate_rBelt09.setRotationPoint(-4.05F, 6.25F, -1.3F);
        this.chestplate_rBelt09.addBox(-0.5F, -0.5F, -0.7F, 1, 1, 5, 0.0F);
        this.lArm = new ModelRenderer(this, 32, 48);
        this.lArm.setRotationPoint(5.0F, 2.0F, -0.0F);
        this.lArm.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        this.setRotateAngle(lArm, 0.0F, 0.0F, -0.10000736613927509F);
        this.chestplate_lBelt03 = new ModelRenderer(this, 122, 4);
        this.chestplate_lBelt03.setRotationPoint(1.15F, 6.35F, -1.9F);
        this.chestplate_lBelt03.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
        this.chestplate_mBelt03 = new ModelRenderer(this, 112, 4);
        this.chestplate_mBelt03.setRotationPoint(0.0F, 9.1F, 2.3F);
        this.chestplate_mBelt03.addBox(-1.0F, 0.0F, -0.5F, 2, 3, 1, 0.0F);
        this.leggings_lGlove = new ModelRenderer(this, 45, 114);
        this.leggings_lGlove.setRotationPoint(1.9F, 2.8F, 0.0F);
        this.leggings_lGlove.addBox(0.0F, 5.5F, -2.0F, 4, 3, 4, 0.0F);
        this.setRotateAngle(leggings_lGlove, 0.0F, 0.0F, 0.40980330836826856F);
        this.boots_lBoots01 = new ModelRenderer(this, 15, 103);
        this.boots_lBoots01.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.boots_lBoots01.addBox(-1.9F, 9.0F, -1.9F, 4, 3, 4, 0.0F);
        this.leggings_rGauntlet = new ModelRenderer(this, 45, 84);
        this.leggings_rGauntlet.mirror = true;
        this.leggings_rGauntlet.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leggings_rGauntlet.addBox(-4.0F, 6.0F, -1.0F, 1, 3, 2, 0.0F);
        this.helmet_Bubble = new ModelRenderer(this, 83, 49);
        this.helmet_Bubble.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_Bubble.addBox(-4.5F, -8.9F, -4.5F, 9, 9, 9, 0.0F);
        this.helmet_lTubeConnector = new ModelRenderer(this, 105, 70);
        this.helmet_lTubeConnector.setRotationPoint(0.0F, 0.0F, 2.8F);
        this.helmet_lTubeConnector.addBox(1.6F, -8.0F, 1.7F, 2, 4, 1, 0.0F);
        this.chestplate_rShoulderPad03b = new ModelRenderer(this, 93, 113);
        this.chestplate_rShoulderPad03b.mirror = true;
        this.chestplate_rShoulderPad03b.setRotationPoint(-0.1F, 0.0F, 0.1F);
        this.chestplate_rShoulderPad03b.addBox(-2.3F, -3.1F, 1.65F, 3, 3, 1, 0.0F);
        this.chestplate_airtankFrameUpper = new ModelRenderer(this, 85, 14);
        this.chestplate_airtankFrameUpper.setRotationPoint(0.0F, -0.9F, 0.4F);
        this.chestplate_airtankFrameUpper.addBox(-3.0F, 2.6F, 1.6F, 6, 3, 3, 0.0F);
        this.chestplate_lShoulderPad01b = new ModelRenderer(this, 95, 95);
        this.chestplate_lShoulderPad01b.setRotationPoint(0.0F, 0.0F, 0.6F);
        this.chestplate_lShoulderPad01b.addBox(-1.7F, -2.1F, -0.45F, 5, 3, 3, 0.0F);
        this.helmet_Lamp5 = new ModelRenderer(this, 60, 83);
        this.helmet_Lamp5.setRotationPoint(0.0F, -1.0F, 0.3F);
        this.helmet_Lamp5.addBox(-1.0F, 0.0F, -1.0F, 2, 2, 2, 0.0F);
        this.setRotateAngle(helmet_Lamp5, 1.4114477660878142F, -0.0F, 0.0F);
        this.chestplate_rShoulderStrap = new ModelRenderer(this, 24, 116);
        this.chestplate_rShoulderStrap.setRotationPoint(1.8F, 0.6F, 0.0F);
        this.chestplate_rShoulderStrap.addBox(-3.5F, -0.5F, -2.95F, 4, 1, 6, 0.0F);
        this.helmet_Lamp3 = new ModelRenderer(this, 70, 76);
        this.helmet_Lamp3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_Lamp3.addBox(-1.5F, -0.7F, -1.5F, 3, 1, 3, 0.0F);
        this.chestplate_plate02 = new ModelRenderer(this, 67, 5);
        this.chestplate_plate02.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_plate02.addBox(-3.5F, 3.0F, -2.8F, 7, 2, 1, 0.0F);
        this.boots_rBoots03 = new ModelRenderer(this, 12, 112);
        this.boots_rBoots03.mirror = true;
        this.boots_rBoots03.setRotationPoint(0.0F, 10.5F, -1.5F);
        this.boots_rBoots03.addBox(-2.05F, -1.5F, -0.8F, 3, 3, 1, 0.0F);
        this.boots_rBoots01 = new ModelRenderer(this, 15, 103);
        this.boots_rBoots01.mirror = true;
        this.boots_rBoots01.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.boots_rBoots01.addBox(-2.1F, 9.0F, -1.9F, 4, 3, 4, 0.0F);
        this.chestplate_plate03 = new ModelRenderer(this, 67, 10);
        this.chestplate_plate03.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.chestplate_plate03.addBox(-3.0F, 4.7F, -2.7F, 6, 2, 1, 0.0F);
        this.chestplate_rBelt01 = new ModelRenderer(this, 111, 0);
        this.chestplate_rBelt01.mirror = true;
        this.chestplate_rBelt01.setRotationPoint(-1.9F, 9.1F, -2.5F);
        this.chestplate_rBelt01.addBox(-2.2F, -1.0F, -0.51F, 3, 2, 1, 0.0F);
        this.setRotateAngle(chestplate_rBelt01, 0.0F, 0.0F, 0.31869712141416456F);
        this.leggings_rSleeve = new ModelRenderer(this, 48, 93);
        this.leggings_rSleeve.mirror = true;
        this.leggings_rSleeve.setRotationPoint(0.0F, 0.0F, -0.0F);
        this.leggings_rSleeve.addBox(-3.4F, -2.1F, -2.4F, 5, 12, 5, 0.0F);
        this.chestplate_lShoulderStrap = new ModelRenderer(this, 24, 116);
        this.chestplate_lShoulderStrap.setRotationPoint(-2.1F, 0.6F, 0.0F);
        this.chestplate_lShoulderStrap.addBox(-0.2F, -0.5F, -2.95F, 4, 1, 6, 0.0F);
        this.helmet_lFrameUpper = new ModelRenderer(this, 73, 52);
        this.helmet_lFrameUpper.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmet_lFrameUpper.addBox(4.01F, -6.8F, -4.2F, 1, 10, 2, 0.0F);
        this.setRotateAngle(helmet_lFrameUpper, -1.0927506446736497F, -0.0F, 0.0F);
        this.chestplate_plate01.addChild(this.chestplate_rBelt03);
        this.chestplate_plate01.addChild(this.chestplate_rBelt07);
        this.chestplate_rShoulderPad01a.addChild(this.chestplate_rShoulderPad01b);
        this.helmet_Lamp1.addChild(this.helmet_LampLense);
        this.chestplate_plate01.addChild(this.chestplate_lBelt04);
        this.boots_lBoots01.addChild(this.boots_lBoots05);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_lBelt05);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_rBelt05);
        this.leggings_lSleeve.addChild(this.leggings_lGauntlet);
        this.helmet_tFrame.addChild(this.helmet_LampStand);
        this.boots_lBoots01.addChild(this.boots_lBoots02);
        this.lArm.addChild(this.chestplate_lShoulderPad01a);
        this.helmet_tube02.addChild(this.helmet_tube03);
        this.chestplate_rShoulderPad01a.addChild(this.chestplate_rShoulderPad02);
        this.chestplate_mStomachPlate.addChild(this.chestplate_rBelt02);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_rBelt06);
        this.chestplate_lShoulderPad01a.addChild(this.chestplate_lShoulderPad02);
        this.helmet_Bubble.addChild(this.helmet_TubeConnector);
        this.lArm.addChild(this.leggings_lSleeve);
        this.helmet_mTubeConnector2.addChild(this.helmet_tube01);
        this.chestplate_mStomachPlate.addChild(this.chestplate_mBelt02);
        this.helmet_Bubble.addChild(this.helmet_tFrame);
        this.chestplate_lShoulderPad01a.addChild(this.chestplate_lShoulderPad03a);
        this.chestplate_plate01.addChild(this.chestplate_rBelt04);
        this.chestplate_mStomachPlate.addChild(this.chestplate_lStomachPlate);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_rAirtankFrame);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_tankPanel);
        this.body.addChild(this.leggings_bodysuit);
        this.chestplate_plate01.addChild(this.chestplate_plate04);
        this.chestplate_mStomachPlate.addChild(this.chestplate_mBelt01);
        this.helmet_Lamp2.addChild(this.helmet_Lamp1);
        this.boots_rBoots01.addChild(this.boots_rBoots02);
        this.chestplate_plate01.addChild(this.chestplate_lBelt07);
        this.helmet_Bubble.addChild(this.helmet_mTubeConnector2);
        this.helmet_tube01.addChild(this.helmet_tube02);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_tubeConnector);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_lAirtankFrame);
        this.helmet_Bubble.addChild(this.helmet_rTubeConnector);
        this.leggings_lLegSuit.addChild(this.leggings_lPad);
        this.chestplate_mStomachPlate.addChild(this.chestplate_rStomachPlate);
        this.lLeg.addChild(this.leggings_lLegSuit);
        this.boots_lBoots01.addChild(this.boots_lBoots03);
        this.leggings_rLegSuit.addChild(this.leggings_rPad);
        this.rLeg.addChild(this.leggings_rLegSuit);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_rCanister);
        this.leggings_rSleeve.addChild(this.chestplate_rShoulderPad01a);
        this.chestplate_rShoulderPad01a.addChild(this.chestplate_rShoulderPad03a);
        this.helmet_tube04.addChild(this.helmet_tube05);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_lCanister);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_lBelt08);
        this.boots_rBoots01.addChild(this.boots_rBoots05);
        this.boots_lBoots01.addChild(this.boots_lBoots04);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_lBelt06);
        this.boots_rBoots01.addChild(this.boots_rBoots04);
        this.chestplate_plate01.addChild(this.chestplate_lBelt09);
        this.body.addChild(this.chestplate_plate01);
        this.body.addChild(this.chestplate_mStomachPlate);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_airtankFrameBottom);
        this.leggings_rSleeve.addChild(this.leggings_rGlove);
        this.helmet_Bubble.addChild(this.helmet_rFrameUpper);
        this.chestplate_mStomachPlate.addChild(this.chestplate_lBelt01);
        this.chestplate_mStomachPlate.addChild(this.chestplate_lBelt02);
        this.chestplate_lShoulderPad03a.addChild(this.chestplate_lShoulderPad03b);
        this.chestplate_mStomachPlate.addChild(this.chestplate_mBelt04);
        this.chestplate_airtankFrameUpper.addChild(this.chestplate_rBelt08);
        this.helmet_tube03.addChild(this.helmet_tube04);
        this.helmet_LampStand.addChild(this.helmet_Lamp2);
        this.chestplate_plate01.addChild(this.chestplate_rBelt09);
        this.chestplate_plate01.addChild(this.chestplate_lBelt03);
        this.chestplate_mStomachPlate.addChild(this.chestplate_mBelt03);
        this.leggings_lSleeve.addChild(this.leggings_lGlove);
        this.lLeg.addChild(this.boots_lBoots01);
        this.leggings_rSleeve.addChild(this.leggings_rGauntlet);
        this.head.addChild(this.helmet_Bubble);
        this.helmet_Bubble.addChild(this.helmet_lTubeConnector);
        this.chestplate_rShoulderPad03a.addChild(this.chestplate_rShoulderPad03b);
        this.body.addChild(this.chestplate_airtankFrameUpper);
        this.chestplate_lShoulderPad01a.addChild(this.chestplate_lShoulderPad01b);
        this.helmet_Lamp2.addChild(this.helmet_Lamp5);
        this.chestplate_rShoulderPad01a.addChild(this.chestplate_rShoulderStrap);
        this.helmet_Lamp2.addChild(this.helmet_Lamp3);
        this.chestplate_plate01.addChild(this.chestplate_plate02);
        this.boots_rBoots01.addChild(this.boots_rBoots03);
        this.rLeg.addChild(this.boots_rBoots01);
        this.chestplate_plate01.addChild(this.chestplate_plate03);
        this.chestplate_mStomachPlate.addChild(this.chestplate_rBelt01);
        this.rArm.addChild(this.leggings_rSleeve);
        this.chestplate_lShoulderPad01a.addChild(this.chestplate_lShoulderStrap);
        this.helmet_Bubble.addChild(this.helmet_lFrameUpper);
    }
    
    @Override
    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale)
    {
        super.bipedBody = body;
        super.bipedHead = head;
        super.bipedRightArm = rArm;
        super.bipedLeftArm = lArm;
        super.bipedLeftLeg = lLeg;
        super.bipedRightLeg = rLeg;
        
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z)
    {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
